version: "2"

services:
  payment-server:
    build: PaymentServer
    image: payment-server
    container_name: payment-server
    ports:
      - "3000:3000"
    links:
      - "bootstrap:ethnode"
      - "redis-db:persistence"

  bootstrap:
    build: GethTestNetwork
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/start.sh
    command: '--mine --datadir=/root/.ethereum/devchain --unlock 0xf1a25936b922d122e03ff95ebd1765b0c2ec8f08,0xbe32869ae95f64fae54353a08ed65e63cef4bac7,0x0ff5c2f25c394a1e69153d658d10fec6a90bc668,0xaae00f546ab93bf19cc59b9dbf59db23076598d7 --password /root/data/password --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --verbosity=2 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=1234 --rpc --rpcaddr="0.0.0.0" init=/root/data/genesis.json'
    volumes:
      - ./GethTestNetwork/password:/root/data/password:ro
      - ./GethTestNetwork/genesis.json:/root/data/genesis.json:ro
      - ./GethTestNetwork/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

  redis-db:
    image: redis:3.0.7
    ports:
      - "6379:6379"
